CREATE SEQUENCE SEQ_TICKET START WITH 1 INCREMENT BY 1;

CREATE TABLE TB_TICKETS(
    ID_TICKET INTEGER DEFAULT NEXTVAL('SEQ_TICKET'),
    NM_TITLE VARCHAR(100) NOT NULL,
    DS_TICKET VARCHAR(255) NOT NULL,
    ST_TICKET VARCHAR(15) NOT NULL,
    ST_PRIORITY VARCHAR(8) NOT NULL,
    NM_RESPONSIBLE VARCHAR(100) NOT NULL,
    CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TB_TICKTES ADD CONSTRAINT PK_TICKET PRIMARY KEY(ID_TICKET);

ALTER TABLE TB_TICKTES ADD CONSTRAINT CK_ST_TICKET CHECK(ST_TICKET IN ('ABERTO', 'EM_ANDAMENTO', 'FINALIZADO'));

ALTER TABLE TB_TICKTES ADD CONSTRAINT CK_ST_PRIORITY CHECK(ST_PRIORITY IN ('BAIXA', 'MEDIA', 'ALTA')); 